### ISSUE TITLE
Add an option to extend rear view mirror draw distance

### ISSUE THREAD

**Issue by Calinou** [0x1F9F1/Open1560#111]
I tried out Open1560 on Linux (using WINE) today, it works great :slightly_smiling_face: 

However, when using modern screen resolutions, the rear view mirror visibly clips things close to the camera, even when the view distance setting is bumped to the maximum value.

Normal view distance (outside the rear view mirror) is pretty good already, so I think there should be a CLI argument to multiply the rear view distance value. It could accept a floating-point number (where `1.0` represents the default distance scale). If that's not feasible, an integer where `100` represents the default scale could be used instead.

**Comment by 0x1F9F1** [comment]
I've added -mirrordist in 18741da231e92985c5e14e9c4eada7ae713e54bd. The default distance is 200, so feel free to try 500 or 1000.
