### ISSUE TITLE
Fatal Error: Failed to load texsheet "mtl/global.tsh"

### ISSUE THREAD

**Issue by New-dev0** [0x1F9F1/Open1560#112]
I am getting error while running the exe, also no Ui is visible

Maybe right here
https://github.com/0x1F9F1/Open1560/blob/bb57eed4a7ee1f2671aa61971913b972544264f6/code/midtown/agiworld/texsheet.h#L131 #

**Comment by 0x1F9F1** [comment]
https://0x1f9f1.github.io/Open1560/ you have to extract the files into your existing midtown madness 1 installation

**Comment by New-dev0** [comment]
Thanks, also you did a Great work
