### ISSUE TITLE
Score bugs

### ISSUE THREAD

**Issue by BenoitAdam94** [0x1F9F1/Open1560#114]
Hey,

Don't know why but the score are a totall mess

Usually indicated a Wrong vehicule, and sometimes a wrong score

Don't know if it comes from Open1560 or a bug from my save files I started years ago

![Open1560_FjT7DsroUf](https://user-images.githubusercontent.com/45485644/182005945-40a66073-9e8e-4b42-83c9-62aa8c008ccc.png)

![Open1560_EvZbu99srW](https://user-images.githubusercontent.com/45485644/182005944-afe4356a-7436-46bf-b3af-74757e707a8e.png)
m

**Comment by BenoitAdam94** [comment]
In the first screen I did North End Navigator with Ford Mustang GT, but it display Ford Cruiser  (altough I tryed with Cruiser before and didn't succeed)

Also I think the score should be 1000 maybe with this vehicle ?

**Comment by 0x1F9F1** [comment]
The time and vehicle correspond to the fastest time. The points is based on the vehicle you used, but that isn't necessarily the same vehicle you used when getting the fastest time (if you've won the race more than once).
