### ISSUE TITLE
Crash /w Error When Breaking Glass !!

### ISSUE THREAD

**Issue by alienfxfiend** [0x1F9F1/Open1560#123]
I get this crash when breaking glass at high speed, has happened to me even /w dgvoodoo2 (though I prefer not to use it) though it doesn't crash when I use the MM Revisited V3 mod (but this mod changes the Sunset from orange to blue so I prefer not to use it.) Can you please fix this bug so I can play MM /w 1560 alone ?! Running Windows 10 64-bit lappy has 8 Gigs RAM & "Intel HD Graphics 4200" 1GB @ 1366x768 startup arguments are: -heapsize 256 -nodamage -nowindow -maxcops 0 -msaa 4 -afilter 16 -scaling 1 -fovfix true -nativeres true. Also [MetroSetting] -> "Graphics Setting" -> Midtown Madness exe set to "High Performance" & I have Comodo Internet Security (HIPS disabled) & I run the shortcut as Admin. I love this game, wish I could play it nonstop, hoping the crash can be rectified !! First happened to me /w the Cadillac crashing into the glass at the potted plants building complex in the top center, then happens during breaking into the glass near the bridge area. I use a bunch of AR mod cars & I have MM Revisited V3 mod disabled cause I don't like the sky textures for the Sunset. Please see attached screenshot....

ABORT: Exception caught during simulate loop, saving replay.
![Crash When Breaking Glass](https://user-images.githubusercontent.com/32994445/201462095-e603a689-731a-4bd4-bf8d-3acea1288e24.png)

**Comment by 0x1F9F1** [comment]
After the game crashes, please upload the Open1560.log from your game's directory

**Comment by alienfxfiend** [comment]
> After the game crashes, please upload the Open1560.log from your game's directory

Alright, will do.

**Comment by alienfxfiend** [comment]
Here you go, I had all other .AR mods (cars basically) disabled yet it crashed —I was driving a Panoz Roadster Gray when I hit into the glass crashing the game (similar to my previous crash /w the MM2 Cars Mod where I was driving an Aston Martin DB7 into the glass.) In this case I had all my commandline arguments removed from the shortcut (I was testing the commandline.txt approach but it did not work (do they each have to be on a new line ? /w the hyphen ?)

[Open1560.log](https://github.com/0x1F9F1/Open1560/files/9996558/Open1560.log)

**Comment by 0x1F9F1** [comment]
Can you run the following powershell command and paste the results?
```
Get-ChildItem | Where-Object {$_.Name.EndsWith('ar', [System.StringComparison]::OrdinalIgnoreCase)} | Foreach-Object { New-Object PSObject -Property @{ Name=$_.Name.ToLower(); Length=$_.Length; Hash=(Get-FileHash -Algorithm SHA1 $_.FullName).Hash } } | Format-Table -Auto
```

**Comment by alienfxfiend** [comment]
Name                                                                 Hash                                                                                Length
----                                                                      ----                                                                                   ------
!!!!!!mm1rv3_audio.ar                                            BC597FF05339704E68A2D344B2327688CF3D2187           1618432
!!!!!!mm1rv3_bettercameras.ar                               A54978135EED3138EF2D04031D1D864BBA4FB647            768352
!!!!!!mm1rv3_cars.ar                                              14C240E80EFE56173309D9A172D62EEFE8F9DDAD            28887280
!!!!!!mm1rv3_cops-in-traffic.ar                                BAB89D768F00B04F6D6B8067D5BAB037827C22A4        1392
!!!!!!mm1rv3_core.ar                                              BA9796DCCF13561422E321152D9996E3AC0B4BC6            82427568
!!!!!!mm1rv3_map-arrows.ar                                   C9EDBDE28AE919209437C6F173566268E548570B          27456
!!!!!!mm1rv3_menu.ar                                            21433577A2B4A2C225611920B7A09FAD571AEA5B            3180080
!!!!!!mm1rv3_opponent-tuning.ar                             2297CB2ADBEC26AEB7D12CA7DA33652B6E72B1A0         79520
!!!!!!mm1rv3_traffic-weight.ar                                 502B03858DDFC9B3C742AF60CEA853D45D923845        8624
!vpredcar.ar                                                         417AE6560A88E2052C50AFD20F1BB12C79E92344           1727856
!vptraffic.ar                                                          1CE5F1ACDF6D384A2BE3B5AA91322DE454AB7FE3           213152
1560.ar                                                                1BDE683C51DBF6C14144A333179A1047DE5927EC              716890
audio.ar                                                               4754F78BD6E537C822E533526882C9360AFA453F         54821984
core.ar                                                                 4058AC179CA888B0BC86F0A0394C70E99FDF56C2        91404016
midtown.madness.v1.0.plus.5.trainer.by.fff.rar       D2995DFCC50CF76F7E33AB59662B9A48882F7B96        353460
ui.ar                                                                     B7CC8EA982C643635CA1D842BD16D740D2678314          19891168
vamm2cars.ar                                                      E51E2A643BE4D5FC2D7D9CD555AE22591C55AAFB         86678224
vblafrance.ar                                                        E6DB3767F43BEB3B6FF41329151D24E2298237CD            5819936
vcbetacars.ar                                                       3547BA60AE13CF0D9D84F6917BF6F06671F449DD           22587472
vp09zr1.ar                                                            2A8F96A984D40D4FE71546A4ACC4BFCB6BDC7C46        4273184
vp55amg.ar                                                         D25EDC0BC4A0BC1A0BA75D90F58D20C5103F59DB        35290864
vpcobra_b.ar                                                        C447D48092DF15D51272618915D349B467F1AA95             25953296
vpeb184.ar                                                           12D01EFA11CA9CF4E1074C01E6D7778FD7E3E027                20302912
vpmp412c.ar                                                        A632738F399B7C3149F869B073E359027455A258           5372256

I have all these .ar mods renamed to .ar.bk so they don't launch, but still crashes when breaking glass sometimes. Also I don't use the trainer.

**Comment by alienfxfiend** [comment]
Sure thing, I formatted the table for your convenience. Please take a look. All other mods have been renamed to .ar.bk, /w only 1560.ar running, still crashes when breaking glass though. ~~> [MM1 List of AR Mods PowerShell Output](https://anotepad.com/notes/x2tqxdnp)

**Comment by alienfxfiend** [comment]
I think disabling all those .ar mods by renaming them to .ar.bk was a big mistake ! (probably still disrupting the game code internally !) I relocated those .ar mods to a different folder & now the game is working so much smoother & w/o any lag ! Hasn't crashed once since I played for a few minutes. Thank you so much for guiding me. I'll close it, if it crashes again I'll re-open.
Cheers mate !
