### ISSUE TITLE
Force Feedback no longer working

### ISSUE THREAD

**Issue by nf555555** [0x1F9F1/Open1560#125]
Hi, with the standard game on Windows 11 using an Xbox Elite Controller force feedback works perfectly once the DirectInput Force Feedback Driver for Xbox Controllers (by Masahiko Morri) is installed, as well as on other controllers that also have drivers for DirectInput Force Feedback available (such as the Logitech F710 and the Nintendo Wii U Pro Controller using the Mayflash adapter). The issue of XInput controller triggers sharing an axis on DirectInput games is slightly annoying but can be worked around manually by remapping the axes, so it's possible to get perfectly functional gamepad support with vibration on the original game.

However, I haven't been able to do so with Open1560. Force Feedback is grayed out and doesn't work. Maybe you've switched to XInput or SDL and haven't implemented rumble? It would be very nice to have an option to disable whatever it is you've done with the input and use the game's default DirectInput implementation so we can use force feedback.

**Comment by 0x1F9F1** [comment]
Indeed, I recently switched to using SDL for controllers and haven't yet implemented rumble support. You can use the `-nosdljoy` cmd param to switch back to DirectInput.
