### ISSUE TITLE
Fanatec CSL DD doesn't work

### ISSUE THREAD

**Issue by ladyeklipse** [0x1F9F1/Open1560#126]
I have a Fanatec CSL DD and surprisingly it (sort of) works with the original midtown.exe, and there is even force feedback, but there is an issue, because of which I cannot reassign buttons to anything other than Joy Btn 1, which seems to be always ON. 
But in Open1560 the wheel isn't detected at all, neither in normal mode nor in compatibility mode.
I can use my 8bitdo XInput controller, but no force feedback on it.

**Comment by 0x1F9F1** [comment]
I recently switched to using SDL for controllers and haven't yet implemented rumble support. You can use the `-nosdljoy` cmd param to switch back to DirectInput.
