### ISSUE TITLE
Crash On Too Many Opponents Finishing

### ISSUE THREAD

**Issue by PantsOrNothing** [0x1F9F1/Open1560#161]
Close to finishing up a mod/race pack, but I've run into a problem that can hopefully be patched before I release it.

In the later checkpoint races I begin to use more than 8 opponents and have noticed that if too many opponents finish the race, the game will crash.

**Comment by PantsOrNothing** [comment]
[Open1560.log](https://github.com/0x1F9F1/Open1560/files/15030765/Open1560.log)

**Comment by 0x1F9F1** [comment]
Thanks the report, but increased opponent limits isn't really a feature of Open1560 yet, just @KcRobin9's version. There is an open issue for it #74, but it's unlikely to be fixed any time soon.
