### ISSUE TITLE
Include Releases in the home page

### ISSUE THREAD

**Issue by ThreeDeeJay** [0x1F9F1/Open1560#165]
![image](https://github.com/0x1F9F1/Open1560/assets/71472458/fa110889-2cc0-4e1c-afc4-ded9d363b048)
Be a lot cooler if you did 👉 😎 👉

**Comment by 0x1F9F1** [comment]
Done, thanks. I turned it off back before I used github releases and people kept downloading the wrong thing. Hopefully it will be fine now.
